server {
    listen 80;
    listen [::]:80;
    server_name fortunetttech.site *.fortunetttech.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name fortunetttech.site *.fortunetttech.site;

    root /var/www/html/fortunett_technologies_;
    index index.php index.html;

    ssl_certificate     /etc/ssl/fortunett/origin.pem;
    ssl_certificate_key /etc/ssl/fortunett/origin.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location / {
        try_files $uri $uri/ $uri.php?$query_string;
    }

    location ~ /\.(env|git|htaccess) { deny all; }
    location ~ ^/(vendor|sql|logs|cache)/ { deny all; }

    client_max_body_size 20M;
    error_log  /var/log/nginx/fortunett_error.log;
    access_log /var/log/nginx/fortunett_access.log;
}
