-- =====================================================
-- SaaS Upgrade Migration
-- Adds platform subscription plans, invoicing,
-- fixes missing tenant_id on 5 tables,
-- and prepares tenants table for subscription tracking.
-- Run once against fortunett_technologies database.
-- =====================================================

USE fortunett_technologies;

-- -------------------------------------------------------
-- 1. Platform Subscription Plans
--    Defines the tiers ISPs can subscribe to on FortuNett
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS platform_subscription_plans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(50) UNIQUE NOT NULL,
    pppoe_fee_per_user DECIMAL(10,2) NOT NULL DEFAULT 25.00 COMMENT 'KSH per PPPoE user per month',
    hotspot_commission_rate DECIMAL(5,4) NOT NULL DEFAULT 0.0300 COMMENT 'Fraction of hotspot revenue e.g. 0.03 = 3%',
    base_monthly_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'Fixed monthly platform fee',
    max_clients INT DEFAULT NULL COMMENT 'NULL = unlimited',
    max_routers INT DEFAULT NULL COMMENT 'NULL = unlimited',
    trial_days INT NOT NULL DEFAULT 30,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO platform_subscription_plans
    (name, slug, pppoe_fee_per_user, hotspot_commission_rate, base_monthly_fee, max_clients, max_routers, trial_days)
VALUES
    ('Starter',    'starter',    25.00, 0.0300, 0.00,    200,  3,   30),
    ('Growth',     'growth',     20.00, 0.0250, 500.00,  1000, 10,  30),
    ('Enterprise', 'enterprise', 15.00, 0.0200, 2000.00, NULL, NULL, 30);

-- -------------------------------------------------------
-- 2. Platform Invoices
--    Super-admin-visible invoices generated by the
--    monthly billing cron, one row per tenant per month.
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS platform_invoices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_number VARCHAR(30) UNIQUE NOT NULL COMMENT 'e.g. INV-2026-03-0001',
    tenant_id INT NOT NULL,
    billing_period DATE NOT NULL COMMENT 'First day of the billed month',
    plan_id INT DEFAULT NULL,

    pppoe_user_count INT NOT NULL DEFAULT 0,
    pppoe_fee_per_user DECIMAL(10,2) NOT NULL DEFAULT 25.00,
    pppoe_subtotal DECIMAL(15,2) GENERATED ALWAYS AS (pppoe_user_count * pppoe_fee_per_user) STORED,

    hotspot_collections DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    hotspot_commission_rate DECIMAL(5,4) NOT NULL DEFAULT 0.0300,
    hotspot_commission DECIMAL(15,2) GENERATED ALWAYS AS (hotspot_collections * hotspot_commission_rate) STORED,

    base_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_due DECIMAL(15,2) GENERATED ALWAYS AS (pppoe_user_count * pppoe_fee_per_user + hotspot_collections * hotspot_commission_rate + base_fee) STORED,

    status ENUM('pending','paid','overdue','waived','cancelled') NOT NULL DEFAULT 'pending',
    due_date DATE NOT NULL,
    paid_at TIMESTAMP NULL,
    payment_method VARCHAR(50) NULL,
    transaction_ref VARCHAR(100) NULL,
    notes TEXT NULL,

    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (plan_id) REFERENCES platform_subscription_plans(id) ON DELETE SET NULL,
    UNIQUE KEY unique_tenant_period (tenant_id, billing_period),
    INDEX idx_status (status),
    INDEX idx_due_date (due_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------
-- 3. Extend tenants table
-- -------------------------------------------------------
ALTER TABLE tenants
    ADD COLUMN IF NOT EXISTS subscription_plan_id INT DEFAULT NULL COMMENT 'FK to platform_subscription_plans',
    ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT NULL COMMENT 'Super-admin internal notes',
    ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMP NULL COMMENT 'When the tenant was last suspended',
    ADD COLUMN IF NOT EXISTS suspended_reason VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(30) NULL;

-- Default all existing tenants to Starter plan
UPDATE tenants SET subscription_plan_id = 1 WHERE subscription_plan_id IS NULL;

ALTER TABLE tenants
    ADD CONSTRAINT fk_tenant_plan FOREIGN KEY (subscription_plan_id)
        REFERENCES platform_subscription_plans(id) ON DELETE SET NULL;

-- -------------------------------------------------------
-- 4. Fix users table: add email_verified column
--    (referenced in login.php but missing from schema)
-- -------------------------------------------------------
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS email_verified TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS is_verified TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS verification_token VARCHAR(80) NULL;

-- Super admin user is pre-verified
UPDATE users SET email_verified = 1, is_verified = 1 WHERE is_super_admin = TRUE;

-- -------------------------------------------------------
-- 5. Fix messages table: add tenant_id
-- -------------------------------------------------------
ALTER TABLE messages
    ADD COLUMN IF NOT EXISTS tenant_id INT DEFAULT NULL COMMENT 'Tenant isolation',
    ADD INDEX IF NOT EXISTS idx_messages_tenant (tenant_id);

-- Back-fill tenant_id from the linked client
UPDATE messages m
    INNER JOIN clients c ON c.id = m.client_id
SET m.tenant_id = c.tenant_id
WHERE m.tenant_id IS NULL AND c.tenant_id IS NOT NULL;

ALTER TABLE messages
    ADD CONSTRAINT IF NOT EXISTS fk_messages_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;

-- -------------------------------------------------------
-- 6. Fix vouchers table: add tenant_id
-- -------------------------------------------------------
ALTER TABLE vouchers
    ADD COLUMN IF NOT EXISTS tenant_id INT DEFAULT NULL COMMENT 'Tenant isolation',
    ADD INDEX IF NOT EXISTS idx_vouchers_tenant (tenant_id);

-- Back-fill from linked package
UPDATE vouchers v
    INNER JOIN packages p ON p.id = v.package_id
SET v.tenant_id = p.tenant_id
WHERE v.tenant_id IS NULL AND p.tenant_id IS NOT NULL;

ALTER TABLE vouchers
    ADD CONSTRAINT IF NOT EXISTS fk_vouchers_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;

-- -------------------------------------------------------
-- 7. Fix customer_sessions table: add tenant_id
-- -------------------------------------------------------
ALTER TABLE customer_sessions
    ADD COLUMN IF NOT EXISTS tenant_id INT DEFAULT NULL COMMENT 'Tenant isolation',
    ADD INDEX IF NOT EXISTS idx_cs_tenant (tenant_id);

UPDATE customer_sessions cs
    INNER JOIN clients c ON c.id = cs.client_id
SET cs.tenant_id = c.tenant_id
WHERE cs.tenant_id IS NULL AND c.tenant_id IS NOT NULL;

ALTER TABLE customer_sessions
    ADD CONSTRAINT IF NOT EXISTS fk_cs_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;

-- -------------------------------------------------------
-- 8. Fix payment_auto_logins table: add tenant_id
-- -------------------------------------------------------
ALTER TABLE payment_auto_logins
    ADD COLUMN IF NOT EXISTS tenant_id INT DEFAULT NULL COMMENT 'Tenant isolation',
    ADD INDEX IF NOT EXISTS idx_pal_tenant (tenant_id);

UPDATE payment_auto_logins pal
    INNER JOIN clients c ON c.id = pal.client_id
SET pal.tenant_id = c.tenant_id
WHERE pal.tenant_id IS NULL AND c.tenant_id IS NOT NULL;

ALTER TABLE payment_auto_logins
    ADD CONSTRAINT IF NOT EXISTS fk_pal_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;

-- -------------------------------------------------------
-- 9. Fix customer_activity_log table: add tenant_id
-- -------------------------------------------------------
ALTER TABLE customer_activity_log
    ADD COLUMN IF NOT EXISTS tenant_id INT DEFAULT NULL COMMENT 'Tenant isolation',
    ADD INDEX IF NOT EXISTS idx_cal_tenant (tenant_id);

UPDATE customer_activity_log cal
    INNER JOIN clients c ON c.id = cal.client_id
SET cal.tenant_id = c.tenant_id
WHERE cal.tenant_id IS NULL AND c.tenant_id IS NOT NULL;

ALTER TABLE customer_activity_log
    ADD CONSTRAINT IF NOT EXISTS fk_cal_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;

-- -------------------------------------------------------
-- 10. Fix mpesa_transactions: add tenant_id
-- -------------------------------------------------------
ALTER TABLE mpesa_transactions
    ADD COLUMN IF NOT EXISTS tenant_id INT DEFAULT NULL COMMENT 'Tenant isolation',
    ADD INDEX IF NOT EXISTS idx_mpesa_tx_tenant (tenant_id);

-- Back-fill tenant_id from the linked client
UPDATE mpesa_transactions mt
    INNER JOIN clients c ON c.id = mt.client_id
SET mt.tenant_id = c.tenant_id
WHERE mt.tenant_id IS NULL AND c.tenant_id IS NOT NULL;

ALTER TABLE mpesa_transactions
    ADD CONSTRAINT IF NOT EXISTS fk_mpesa_tx_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;

-- -------------------------------------------------------
-- 11. Record this migration
-- -------------------------------------------------------
INSERT IGNORE INTO schema_migrations (migration_name) VALUES ('2026-03-26-saas-upgrade');
