const { chromium } = require('playwright');
const { execFileSync } = require('child_process');
const fs = require('fs');
const assert = require('assert');
(async () => {
    const html = execFileSync('php', ['-n', '-r', "date_default_timezone_set('Africa/Nairobi'); $canGrantOwnerAccess=true; $packages=[['id'=>1,'name'=>'Test package','price'=>100,'type'=>'hotspot']]; require 'includes/customer_expiry_modal.php';"], {encoding:'utf8'});
    const browser = await chromium.launch({executablePath:process.env.PORTAL_BROWSER || 'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
    try {
        const page = await browser.newPage({viewport:{width:1000,height:850}});
        const errors=[]; page.on('pageerror', e=>errors.push(e.message));
        await page.setContent('<html data-theme="dark"><body style="background:#141413;color:#e2e2e0"><button id="opener">Open</button>'+html.replace(/<script[^>]*src="expiry-modal.js[^"\s]*"><\/script>/,'').replace(/<link[^>]*>/,'')+'</body></html>');
        await page.addStyleTag({content:fs.readFileSync('expiry-modal.css','utf8')});
        await page.addScriptTag({content:fs.readFileSync('expiry-modal.js','utf8')});
        await page.evaluate(()=>{
            window.calls=[];
            window.applyOwnerAccess=()=>calls.push('owner'); window.applySetDate=()=>calls.push('date'); window.applyChangePackage=()=>calls.push('package');
            window.closeExpiryModal=()=>{if(ExpiryModal.close()) document.getElementById('expiryModal').style.display='none';};
            document.getElementById('opener').focus();
            document.getElementById('expiryModal').style.display='flex';
            ExpiryModal.open({full_name:'Owner test',connection_type:'hotspot',expiry_date:'2026-01-01 12:00:00'});
        });
        assert.strictEqual(await page.locator('#expiryAction').inputValue(),'date');
        await page.locator('#expiryCalendar').fill('2028-01-01');
        await page.locator('#expirySave').click();
        assert.deepStrictEqual(await page.evaluate(()=>calls),['date']);
        await page.locator('#expiryAction').selectOption('owner');
        await page.getByRole('button',{name:'10 years',exact:true}).click();
        await page.locator('#expirySave').click();
        assert.deepStrictEqual(await page.evaluate(()=>calls),['date','owner']);
        await page.locator('#expiryCalendar').fill('2020-01-01');
        await page.locator('#expirySave').click();
        assert.match(await page.locator('#expiryFeedback').textContent(),/future date/);
        await page.locator('#expiryAction').selectOption('package');
        assert(await page.locator('#expiryPackageSection').isVisible());
        assert(!(await page.locator('#expiryCalendar').isVisible()));
        await page.evaluate(()=>ExpiryModal.open({full_name:'PPPoE test',connection_type:'pppoe',expiry_date:'2026-01-01 12:00:00'}));
        assert.strictEqual(await page.locator('#expiryAction').inputValue(),'date');
        assert(await page.locator('#expiryOwnerOption').isDisabled());
        await page.locator('#expiryCalendar').fill('2027-01-01'); await page.locator('#expirySave').click();
        assert.strictEqual(await page.locator('#expiryFeedback').textContent(),'');
        assert.deepStrictEqual(await page.evaluate(()=>calls),['date','owner','date']);
        await page.locator('#expiryCalendar').fill('2030-01-01');
        await page.locator('#expiryClock').fill('12:00');
        await page.getByRole('button',{name:'+7 Days',exact:true}).click();
        assert.strictEqual(await page.locator('#expiryCalendar').inputValue(),'2030-01-08');
        await page.locator('#expiryCalendar').fill('2030-01-31');
        await page.getByRole('button',{name:'+1 Month',exact:true}).click();
        assert.strictEqual(await page.locator('#expiryCalendar').inputValue(),'2030-02-28');
        assert.strictEqual(await page.locator('#expiryClock').inputValue(),'12:00');
        await page.getByRole('button',{name:'+12 Hours',exact:true}).click();
        assert.strictEqual(await page.locator('#expiryCalendar').inputValue(),'2030-03-01');
        assert.strictEqual(await page.locator('#expiryClock').inputValue(),'00:00');
        await page.evaluate(()=>ExpiryModal.open({full_name:'No expiry',connection_type:'pppoe'}));
        await page.getByRole('button',{name:'+1 Hour',exact:true}).click();
        await page.locator('#expirySave').click();
        assert.strictEqual((await page.evaluate(()=>calls)).at(-1),'date');
        await page.evaluate(()=>ExpiryModal.pending(true)); assert(await page.locator('#expirySave').isDisabled());
        await page.evaluate(()=>ExpiryModal.pending(false));
        await page.evaluate(()=>ExpiryModal.open({full_name:'Owner test',connection_type:'hotspot',expiry_date:'2026-01-01 12:00:00'}));
        await page.locator('#currentExpiryDisplay').evaluate(el=>el.textContent='Jan 1, 2026, 12:00 PM');
        await page.setViewportSize({width:375,height:740});
        assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
        await page.locator('#expirySave').scrollIntoViewIfNeeded();
        assert(await page.locator('#expirySave').isVisible());
        await page.screenshot({path:'artifacts/expiry-modal-mobile.png'});
        await page.setViewportSize({width:1000,height:850});
        await page.screenshot({path:'artifacts/expiry-modal-dark.png'});
        await page.evaluate(()=>document.documentElement.dataset.theme='light');
        assert.strictEqual(await page.locator('.expiry-card').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(34, 34, 33)');
        assert.strictEqual(await page.locator('#expiryTitle').evaluate(el=>getComputedStyle(el).color),'rgb(226, 226, 224)');
        for (const selector of ['#expiryCalendar','#expiryClock','#expiryAction']) {
            const style=await page.locator(selector).evaluate(el=>({background:getComputedStyle(el).backgroundColor,scheme:getComputedStyle(el).colorScheme}));
            assert.strictEqual(style.background,'rgb(28, 28, 27)');
            assert.strictEqual(style.scheme,'dark');
        }
        await page.screenshot({path:'artifacts/expiry-modal-light.png'});
        await page.keyboard.press('Escape');
        assert(!(await page.locator('#expiryModal').isVisible()));
        assert.deepStrictEqual(errors,[]);
        console.log('PASS: hotspot/PPPoE extensions, missing expiry, add-time buttons, owner validation, package mode, busy state, Clients theme, mobile layout and Escape');
        const dashboard = fs.readFileSync('dashboard.php','utf8');
        const start = dashboard.indexOf('    if (Array.isArray(s.alerts)) {');
        const end = dashboard.indexOf('    // Most Active Users table',start);
        const alertRenderer = dashboard.slice(start,end);
        await page.route('https://expiry-test.local/**', route=>route.fulfill({contentType:'text/html',body:'<div class="alerts-list"></div>'}));
        await page.goto('https://expiry-test.local/dashboard.php');
        await page.evaluate(code=>{
            window.renderAlerts = new Function('s',code);
            renderAlerts({alerts:[{type:'warning',title:'Expired <account>',message:'Review overdue accounts',time:'Now',link:'clients.php?expiry=overdue_active'}]});
        },alertRenderer);
        assert.strictEqual(await page.locator('.alert-item').getAttribute('href'),'https://expiry-test.local/clients.php?expiry=overdue_active');
        assert.strictEqual(await page.locator('.alert-title').textContent(),'Expired <account>');
        await page.evaluate(()=>renderAlerts({alerts:[]}));
        assert.strictEqual(await page.locator('.alert-item').count(),0);
        assert.match(await page.locator('.alerts-list').textContent(),/No new alerts/);
        console.log('PASS: dashboard alerts link to filtered accounts, escape text and clear resolved warnings');
    } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exit(1);});
