const {chromium} = require('playwright');
const assert = require('assert');
const fs = require('fs');
(async () => {
    const browser = await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
    const page = await browser.newPage({viewport:{width:1440,height:1000}});
    const base = 'http://127.0.0.1:8766';
    const errors=[]; page.on('pageerror', e=>errors.push(e.message));
    fs.mkdirSync('artifacts',{recursive:true});
 await page.route('https://fonts.googleapis.com/**', route=>route.abort());
    try {
        await page.goto(base+'/index.php');
        assert(page.url().endsWith('/login.php'));
        assert.match(await page.locator('h1').textContent(), /Your network/);
        await page.screenshot({path:'artifacts/fortunett-landing-desktop.png',fullPage:true});
        await page.locator('.theme-toggle').click();
        assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
        await page.reload();
        assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
        await page.locator('.theme-toggle').click();
        await page.setViewportSize({width:390,height:844});
        assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth));
        await page.screenshot({path:'artifacts/fortunett-landing-mobile.png',fullPage:true});
        await page.locator('summary').first().click();
        assert(await page.locator('details').first().getAttribute('open') !== null);
        await page.locator('.nav-signin').click();
        assert(await page.locator('#login-form').isVisible());
        await page.locator('#username').fill('ghetto-admin');
        await page.locator('#password').fill('incorrect');
        await page.locator('#show-password').click();
        assert.equal(await page.locator('#password').getAttribute('type'),'text');
        await Promise.all([page.waitForNavigation(),page.locator('[type=submit]').click()]);
        assert.match(await page.locator('[role=alert]').textContent(), /Invalid username or password/);
        assert.equal(await page.locator('#username').inputValue(),'ghetto-admin');
        await page.locator('#password').fill('Local-test-only-42!');
        await Promise.all([page.waitForNavigation(),page.locator('[type=submit]').click()]);
        assert.match(await page.locator('[role=alert]').textContent(),/Sign in on your own workspace/);
        assert.equal(await page.locator('[role=alert] a').getAttribute('href'),'https://ghettohlink.fortunetttech.site/login.php?signin=1');
        await page.goto(base+'/login.php?tenant=ghettohlink');
        assert(await page.locator('#hero-title').isVisible());
        await page.locator('.nav-signin').click();
        assert.match(await page.locator('.login-card h2').textContent(),/Ghetto Link/);
        await page.screenshot({path:'artifacts/fortunett-login-mobile.png',fullPage:true});
        await page.setViewportSize({width:1440,height:1000});
        await page.screenshot({path:'artifacts/fortunett-login-desktop.png',fullPage:true});
        async function attempt(user) {
            await page.locator('#username').fill(user);
            await page.locator('#password').fill('Local-test-only-42!');
            await Promise.all([page.waitForNavigation(),page.locator('[type=submit]').click()]);
        }
        await attempt('ecoland-admin');
        assert.match(await page.locator('[role=alert]').textContent(),/Invalid username or password/);
        await attempt('unverified');
        assert.match(await page.locator('[role=alert]').textContent(),/verify your email/);
        await page.evaluate(()=>document.querySelector('[name=csrf]').value='invalid');
        await attempt('ghetto-admin');
        assert.match(await page.locator('[role=alert]').textContent(),/session expired/);
        await attempt('ghetto-admin');
        assert(page.url().endsWith('/dashboard.php'));
        assert.equal(JSON.parse(await page.locator('body').textContent()).tenant,9);
        await page.goto(base+'/logout.php');
        await page.goto(base+'/login.php?signin=1');
        await attempt('super-admin');
        assert(page.url().endsWith('/super_admin/index.php'));
        assert.equal(JSON.parse(await page.locator('body').textContent()).super,true);
        await page.goto(base+'/logout.php');
        const tenantPage=await page.request.get(base+'/login.php',{headers:{Host:'ecolandattic.fortunetttech.site'}});
        assert.match(await tenantPage.text(),/Ecoland Attic/);
        const publicPage=await page.request.get(base+'/login.php?tenant=ghettohlink',{headers:{Host:'www.fortunetttech.site'}});
        assert.match(await publicPage.text(),/id="hero-title"/);
        const unknown=await page.request.get(base+'/login.php',{headers:{Host:'missing.fortunetttech.site'}});
        assert.equal(unknown.status(),404);
        assert.deepEqual(errors,[]);
        console.log('PASS public landing, mobile layouts, theme, password visibility, errors, CSRF, tenant isolation, tenant login, verification and super-admin routing');
    } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exit(1);});
